### ISSUE TITLE
add github action

### ISSUE THREAD

**Issue by ym-project** [ym-project/favicon-generator#2]
Add github action to publish a package to the npm registry.
Action must be run after release only.

Template
```yml
name: Publish npm package

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
```
